Repository MenuraDewalegama/Conference-Management-Tool, pull requests merged in 2021-05, with the labels that each got.

#9 Feat/8/initialize frontend project structure
  Conference-Management-Tool-app-frontend/App.jsx
  Conference-Management-Tool-app-frontend/LICENSE
  Conference-Management-Tool-app-frontend/README.md
  Conference-Management-Tool-app-frontend/index.html
  Conference-Management-Tool-app-frontend/index.jsx
  Conference-Management-Tool-app-frontend/package.json
  Conference-Management-Tool-app-frontend/src/components/.gitkeep
  Conference-Management-Tool-app-frontend/src/context/.gitkeep
  Conference-Management-Tool-app-frontend/src/service/.gitkeep
Labels: feat

#11 Feat/10/install basic dependencies for backend
  Conference-Management-Tool-app-backend/.gitkeep
  Conference-Management-Tool-app-backend/package.json
Labels: feat

#13 Feat/12/install basic dependencies for frontend
  Conference-Management-Tool-app-frontend/package.json
Labels: feat

#17 Implement basic functionality of navigation bar and landing page.
  Conference-Management-Tool-app-frontend/App.jsx
  Conference-Management-Tool-app-frontend/index.html
  Conference-Management-Tool-app-frontend/index.jsx
  Conference-Management-Tool-app-frontend/package.json
  Conference-Management-Tool-app-frontend/public/assets/.gitkeep
  Conference-Management-Tool-app-frontend/src/components/conference/ConferenceHolder.css
  Conference-Management-Tool-app-frontend/src/components/conference/ConferenceHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/main/Main.jsx
  Conference-Management-Tool-app-frontend/src/components/navigation-bar/NavigationBar.css
  Conference-Management-Tool-app-frontend/src/components/navigation-bar/NavigationBar.jsx
  Conference-Management-Tool-app-frontend/src/context/user.context.js
  Conference-Management-Tool-app-frontend/src/service/.gitkeep
  Conference-Management-Tool-app-frontend/src/service/axios.service.js
Labels: feat

#19 Feat/18/implement basic backend services
  Conference-Management-Tool-app-backend/.env
  Conference-Management-Tool-app-backend/app.js
  Conference-Management-Tool-app-backend/src/service/.gitkeep
  Conference-Management-Tool-app-backend/src/service/database.service.js
  Conference-Management-Tool-app-backend/src/util/.gitkeep
  Conference-Management-Tool-app-backend/src/util/database.util.js
Labels: feat

#21 Feature/4/creat dashboard in ront end for admin
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.css
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.jsx
  Conference-Management-Tool-app-frontend/src/components/main/Main.jsx
  Conference-Management-Tool-app-frontend/src/components/navigation-bar/NavigationBar.jsx
Labels: feat

#27 Feature/4/creat dashboard in ront end for admin
  Conference-Management-Tool-app-frontend/assets/css/material-dashboard.css
  Conference-Management-Tool-app-frontend/index.html
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/ConferenceViewCard.jsx
Labels: enhancement

#29 Applied Changes closed #28
  Conference-Management-Tool-app-frontend/index.html
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.css
Labels: bug

#31 Enhancement/22/enhancement 01 for dash board UI
  Conference-Management-Tool-app-frontend/assets/css/material-dashboard.css
  Conference-Management-Tool-app-frontend/index.html
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.css
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/ConferenceView/ConferenceViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/ConferenceViewCard.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersView/UsersViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/WorkShopView/WorkShopViewHolder.jsx
Labels: enhancement

#33 Feature/32/create UI to add writers and reviewers
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.css
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoardHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/ConferenceViews/ConferenceViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersView/UsersViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/CreateUserView.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/UsersViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/WorkShopViews/WorkShopViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/main/Main.jsx
Labels: enhancement

#35 Feature/34/implement backend api services for manage writers and reviewers
  Conference-Management-Tool-app-backend/app.js
  Conference-Management-Tool-app-backend/src/api/internalUser.api.js
  Conference-Management-Tool-app-backend/src/dal/internalUser.dao.js
  Conference-Management-Tool-app-backend/src/routes/internalUser.routes.js
  Conference-Management-Tool-app-backend/src/service/database.service.js
  Conference-Management-Tool-app-backend/src/util/database.util.js
Labels: feat

#37 Enhancement/36/combined front end and back end of internal users
  Conference-Management-Tool-app-frontend/.env
  Conference-Management-Tool-app-frontend/index.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoardHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUserListItem.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUsers.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUsersViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/UsersViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/context/internalUser.context.js
  Conference-Management-Tool-app-frontend/src/service/internalUser.service.js
Labels: enhancement

#39 Enhancement/38/enhancement of internal users view UI
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUserListItem.jsx
Labels: enhancement

#41 crud operations Done excluding image part
  Conference-Management-Tool-app-backend/src/api/internalUser.api.js
  Conference-Management-Tool-app-backend/src/dal/internalUser.dao.js
  Conference-Management-Tool-app-backend/src/routes/internalUser.routes.js
Labels: enhancement

#43 Continue crude operation on frontend
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoardHolder.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/CreateEditUserView.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/CreateUserView.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUsers.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUsersViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/context/internalUser.context.js
  Conference-Management-Tool-app-frontend/src/service/internalUser.service.js
Labels: enhancement

#45 Feat/20/implement conference posts crud
  .gitignore
  Conference-Management-Tool-app-backend/.env
  Conference-Management-Tool-app-backend/app.js
  Conference-Management-Tool-app-backend/public/assets/.gitkeep
  Conference-Management-Tool-app-backend/src/api/.gitkeep
  Conference-Management-Tool-app-backend/src/api/conference-post.api.js
  Conference-Management-Tool-app-backend/src/dal/.gitkeep
  Conference-Management-Tool-app-backend/src/dal/conference-post-dao.js
  Conference-Management-Tool-app-backend/src/routes/.gitkeep
  Conference-Management-Tool-app-backend/src/routes/conference-post.route.js
  Conference-Management-Tool-app-backend/src/routes/validation/common.validation.js
  Conference-Management-Tool-app-backend/src/routes/validation/conference-post.validation.js
  Conference-Management-Tool-app-backend/src/service/dir.service.js
  Conference-Management-Tool-app-backend/src/service/id-generation.service.js
  package-lock.json
  package.json
Labels: feat

#46 implementation done closed #44
  Conference-Management-Tool-app-frontend/src/components/dashBoard/DashBoard.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/CreateEditUserView.jsx
Labels: enhancement

#47 Feat/20/implement conference posts crud
  Conference-Management-Tool-app-backend/package.json
  Conference-Management-Tool-app-backend/src/routes/conference-post.route.js
  Conference-Management-Tool-app-backend/src/routes/validation/common.validation.js
  Conference-Management-Tool-app-backend/test/api/conference-post-api.test.js
Labels: feat

#49 Implement update operation for internal users
  Conference-Management-Tool-app-backend/src/api/internalUser.api.js
  Conference-Management-Tool-app-backend/src/dal/internalUser.dao.js
  Conference-Management-Tool-app-backend/src/routes/internalUser.routes.js
Labels: enhancement

#52 resolved closed #51
  Conference-Management-Tool-app-backend/src/api/internalUser.api.js
  Conference-Management-Tool-app-backend/src/routes/internalUser.routes.js
  Conference-Management-Tool-app-frontend/src/service/internalUser.service.js
Labels: bug

#53 Enhancement/50/implement update function in frontend for internal users
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/CreateEditUserView.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUserListItem.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUsers.jsx
  Conference-Management-Tool-app-frontend/src/components/dashBoard/SubModules/UsersViews/InternalUsersViewHolder.jsx
  Conference-Management-Tool-app-frontend/src/context/internalUser.context.js
  Conference-Management-Tool-app-frontend/src/service/internalUser.service.js
Labels: enhancement
